### ISSUE TITLE
Update to 1.6.1

### ISSUE THREAD

**Issue by danielbonnell** [hiravgandhi/angularjs-rails#111]
Is it possible to bump up to 1.6.1? Thanks!

**Comment by amdstorm** [comment]
Made a fork for this, till the upgrade is ready. 

https://github.com/talenox/angularjs-rails

**Comment by danielbonnell** [comment]
@amdstorm I'll use your fork for now. Thanks

**Comment by hiravgandhi** [comment]
Hey guys,

I have updated the gem in both RubyGems and here in GIT.
