### ISSUE TITLE
No way to auto-upgrade the gem 1.6.2 loaded from RubyGems

### ISSUE THREAD

**Issue by SkatEddy** [hiravgandhi/angularjs-rails#115]
"Thanks to Nick Clark, we have an auto-upgrader that will upgrade the package to the latest version." Maybe in master branch, unfortunately the gem 1.6.2 loaded from RubyGems missing all auto-upgrader related parts (Rakefile et al). Please include this.

**Comment by hiravgandhi** [comment]
@SkatEddy - I keep the gem updated on my side - the autoupdater helps me keep the gem updated. I have removed this from the README to ease any confusion.
