### ISSUE TITLE
"Error: [$injector:unpr] Unknown provider: tProvider <- t" when pushed to production

### ISSUE THREAD

**Issue by jasonfb** [hiravgandhi/angularjs-rails#39]
Brand new Rails 4.0.2 app. AngularJS works fine in development, but when pushed to production (Heroku) I get this error in the console when a page loads:

Error: [$injector:unpr] Unknown provider: tProvider <- t

Gemfile: https://gist.github.com/jasonfb/8274859

application.js file looks like this https://gist.github.com/jasonfb/8274880

the only angular class in my application looks like this: https://gist.github.com/jasonfb/8274925 

is there something non-minisafe about the way I wrote the angular js controller?

**Comment by hiteshranaut** [comment]
@jasonfb thanks 
`config.assets.js_compressor = Uglifier.new(mangle: false)` worked for me.
but I dont understand why it's needed?
