### ISSUE TITLE
1.2.12.1 release breaks semver 

### ISSUE THREAD

**Issue by djcp** [hiravgandhi/angularjs-rails#49]
Gemfile pessimistic versions rely on correct MAJOR.MINOR.PATCH semver usage.

For instance, 

```ruby
gem 'angularjs-rails', '~> 1.2.12'
``` 
won't install 1.2.12.1 as it doesn't match.

```ruby
gem 'angularjs-rails', '~> 1.2.12.x'
```
*will* install 1.2.12.1 (or 1.2.12.2, etc), but *won't * install 1.2.13 when it's released. 

So. . . 1.2.12.1 probably should've been released as 1.2.13 as it is technically a PATCH, fixing the Rails 4 problems (and probably other issues, but the rails 4 breakage was the one that bit me).

FYI. I wouldn't yank 1.2.12.1 as yanking gems can cause annoying issues, but it might be nice to re-release 1.2.13 quickly so we can use pessimistic versioning again. 

Thanks!

**Comment by matthewd** [comment]
This is old, but just in case someone else comes across it, and is at risk of being misled:

``` ruby
Gem::Requirement.new('~> 1.2.12').satisfied_by? Gem::Version.new('1.2.12.1')  # => true
```
