### ISSUE TITLE
1.3.36 version breaks upgrade

### ISSUE THREAD

**Issue by redox** [hiravgandhi/angularjs-rails#78]
Something weird happened with the 1.3.36 version, it takes over the newest one because of semantic versioning:

![screen shot 2015-01-09 at 12 47 42](https://cloud.githubusercontent.com/assets/29529/5679315/e2834d3a-97fd-11e4-99bf-ca9f326f21d1.png)

**Comment by hiravgandhi** [comment]
Yup I yanked it. It should have disappeared now on RubyGems.

**Comment by redox** [comment]
Alright :+1:  Thanks
