### ISSUE TITLE
Please upgrade to 1.4-rc.2

### ISSUE THREAD

**Issue by eamon-hguk** [hiravgandhi/angularjs-rails#82]

**Comment by pisaacs** [comment]
1.4 isn't out as yet. Are you referring to rc.2? If so, can you revise the title?

**Comment by eamon-hguk** [comment]
Yes I am, sorry about that.

**Comment by hildevestol** [comment]
I would also love to be able to use 1.4.0-rc.2 

> 1.4 isn't out as yet. Are you referring to rc.2? If so, can you revise the title?

Perhaps u @eamon-hguk should revise the title as asked?
