### ISSUE TITLE
Question: Branch with Angular2 Beta

### ISSUE THREAD

**Issue by fdibartolo** [hiravgandhi/angularjs-rails#86]
Hey, thanks for the gem in the first place.
Just wondering if you plan to have a branch while Angular2 is in beta, so that we can reference for our own apps.
Thanks again!

**Comment by hiravgandhi** [comment]
Take a look at the unstable folder in the gem and README to see instructions on how to use Angular 2.

**Comment by fdibartolo** [comment]
Thanks a lot!
I am closing the issue.
