### ISSUE TITLE
Upgrade to 1.2.28

### ISSUE THREAD

**Issue by voltechs** [hiravgandhi/angularjs-rails#88]

**Comment by voltechs** [comment]
Does a comment need to trigger the auto upgrader?

**Comment by voltechs** [comment]
*sigh* what does this take? Hello?

**Comment by hiravgandhi** [comment]
hey dale - I was out on vacation and did not have any access to a computer for the past two weeks.

the upgrade script I use to keep the gem up to date only looks at the 1.4.x branch and the 2.x branch of AngularJS. I would be more than happy to take the following:

1) A pull request that upgrades the current script I have right now to create three gems - one for each of the branches (1.2.x, 1.4.x, 2.x)
2) A pull request specifically for 1.2.28.
3) Some time to manually update the scripts myself

Are you up for contributing either option 1 or 2?

**Comment by voltechs** [comment]
Hey Hirav,

No promises, but I will definitely take a peek this weekend. Didn't even cross my mind that the updater might be in the repo. I just thought it was a shell script on a server somewhere haha!

I'll do my best to clear some time and remember to take a look. :+1:
