### ISSUE TITLE
Angular2 Now In Beta

### ISSUE THREAD

**Issue by ctilley83** [hiravgandhi/angularjs-rails#97]
The Angular 2 version in the unstable folder is very old.  Do you plan on updating this gem soon?  Is there a way I can upgrade manually without breaking the gem?

**Comment by overlox** [comment]
+1

**Comment by fregdee** [comment]
+1

**Comment by johnknapp** [comment]
Needed! Is there an expected timeline for this?

**Comment by Lujaw** [comment]
+1

**Comment by hiravgandhi** [comment]
Hi guys,

Sorry, I have been busy getting married. I have updated the gem to 1.5.0 which includes AngularJS 2.0.0-beta6. I would take pull requests that allows me to build two gems - one for the stable and one for the unstable. That way, I am not constrained to releasing Angular 2.0 beta gems only when a stable version in the 1.x.x series is released.
